### ISSUE TITLE
Lyo libraries referenced that are not available

### ISSUE THREAD

**Issue by gpgreen** [Open-MBEE/doors-ng-client#1]
Several org.eclipse.lyo.oslc4j libraries are referenced in pom.xml that don't seem to be available. The version numbers are 3.0.0-20160406.xxxxx. These are also not included in the Open-MBEE mvn-repo project.

**Comment by EDKarlsson** [comment]
Just added the jars to https://github.com/Open-MBEE/mvn-repo
